apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ucl-assistant-tls
  namespace: default
spec:
  secretName: ucl-assistant-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.assistant.mbell.me
  dnsNames:
  - api.assistant.mbell.me
  acme:
    config:
    - http01:
        ingress: ucl-assistant-web
      domains:
      - api.assistant.mbell.me